### ISSUE TITLE
I am getting the following error, how to resolve?

### ISSUE THREAD

**Issue by guocity** [neondatabase/serverless-cfworker-demo#3]
## code:
import { Client } from '@neondatabase/serverless';
interface Env { DATABASE_URL: string; }

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const client = new Client(env.DATABASE_URL);
    await client.connect();
    const { rows: [{ now }] } = await client.query('select now();');
    ctx.waitUntil(client.end());  // this doesn’t hold up the response
    return new Response(now);
  }
}

## error:
wrangler dev                    
Delegating to locally-installed wrangler@2.12.0 over global wrangler@2.13.0...
Run `npx wrangler dev` to use the local version directly.

 ⛅️ wrangler 2.12.0 (update available 2.13.0)
-------------------------------------------------------
⬣ Listening at http://0.0.0.0:8787
- http://127.0.0.1:8787
- http://192.168.1.19:8787
Total Upload: 220.65 KiB / gzip: 54.03 KiB
A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code and events related to the Promise's I/O context have already finished.
1:28:37 AM GET / 500
✘ [ERROR] Uncaught (in response) Error: The script will never generate a response.

**Comment by jawj** [comment]
Thanks. I suspect the `DATABASE_URL` environment variable is not available to the Worker?

For `npx wrangler dev` and `npx wrangler publish`, set it by running `npx wrangler secret put DATABASE_URL`.

For `npx wrangler dev --local`, set it by creating a file `.dev.vars` with the line `DATABASE_URL=...`.

In either case the value should be the full connection string, including password, i.e. something like `postgres://user:pass@xyz.neon.tech/neondb`.

Please let me know if that fixes things. If it does, I'll then try to take a look why this isn't giving a more informative error message.

**Comment by guocity** [comment]
I found out the error come from need a wsProxy websocket after i run dev flag:

[mf:err] Unhandled Promise Rejection: Error: No WebSocket proxy is configured on the Neon serverless driver for database host "xyz-postgres.render.com". If "xyz-postgres.render.com" is the host you expected, then you'll need to set the 'wsProxy' option on the driver (see: https://github.com/neondatabase/serverless#run-your-own-websocket-proxy).

**Comment by jawj** [comment]
Ah, OK. Yes, non-Neon databases will need a separate WebSocket proxy to make them accessible from Cloudflare Workers and similar.

**Comment by guocity** [comment]
i see, so i can't use non-Neon db connection directly

**Comment by jawj** [comment]
That's right. Neon provides WebSocket access to its DB servers, but this is not a standard Postgres feature. The link provided in the error message gives [instructions on running your own WebSocket proxy](https://github.com/neondatabase/serverless#run-your-own-websocket-proxy) (but this may or may not be suitable to your use case).
